### ISSUE TITLE
Not working on macOS IntelliJ

### ISSUE THREAD

**Issue by NTMS2017** [putraxor/flutter-book-app#1]
Hi,
Thanks for the best tutorial. Unfortunetly I couldn't run on my using the source. 
This is the crash report.

Any help please?
----------------------
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --preview-dart-2 --device-id=emulator-5554 lib/main.dart

## exception

FileSystemException: FileSystemException: Exists failed, path = '/Users/niyazitoros/Applications/Visual Studio Code.app/Contents' (OS Error: Permission denied, errno = 13)

```
#0      _Directory.existsSync (dart:io/directory_impl.dart:73)
#1      ForwardingFileSystemEntity.existsSync (package:file/src/forwarding/forwarding_file_system_entity.dart:45)
#2      VsCode._findInstalled (package:flutter_tools/src/vscode/vscode.dart:166)
#3      VsCode._installedMacOS (package:flutter_tools/src/vscode/vscode.dart:96)
#4      VsCode.allInstalled (package:flutter_tools/src/vscode/vscode.dart:77)
#5      VsCodeValidator.installedValidators (package:flutter_tools/src/vscode/vscode_validator.dart:20)
#6      _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:56)
#7      Doctor.validators (package:flutter_tools/src/doctor.dart:79)
#8      Doctor.workflows (package:flutter_tools/src/doctor.dart:93)
#9      Doctor.canLaunchAnything (package:flutter_tools/src/doctor.dart:194)
#10     FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:357)
<asynchronous suspension>
#11     RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:252)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:323)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:279)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1126)
#16     _CustomZone.run (dart:async/zone.dart:1023)
#17     runZoned (dart:async/zone.dart:1501)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:270)
#20     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:309)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1126)
#24     _CustomZone.run (dart:async/zone.dart:1023)
#25     runZoned (dart:async/zone.dart:1501)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:265)
<asynchronous suspension>
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#29     new Future.sync (dart:async/future.dart:222)
#30     CommandRunner.run (package:args/command_runner.dart:109)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:174)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:54)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1126)
#35     _CustomZone.run (dart:async/zone.dart:1023)
#36     runZoned (dart:async/zone.dart:1501)
#37     AppContext.run (package:flutter_tools/src/base/context.dart:141)
<asynchronous suspension>
#38     runInContext (package:flutter_tools/src/context_runner.dart:42)
<asynchronous suspension>
#39     run (package:flutter_tools/runner.dart:49)
#40     main (package:flutter_tools/executable.dart:48)
<asynchronous suspension>
#41     main (file:///Users/niyazitoros/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:277)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.3.6-pre.21, on Mac OS X 10.13.4 17E202, locale tr-CY)
    • Flutter version 0.3.6-pre.21 at /Users/niyazitoros/flutter
    • Framework revision 4bb7496b62 (6 hours ago), 2018-04-25 22:16:59 -0700
    • Engine revision cb2092b3fd
    • Dart version 2.0.0-dev.50.0.flutter-8d4074175f

[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 9.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3, Build version 9E145
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.0

• No issues found!
```

**Comment by putraxor** [comment]
It is a permission issue, try running your command with `sudo`

**Comment by NTMS2017** [comment]
I am on macOS high Sierra and using IntelliJ IDE. I try to create a new app and I had same crash report. 
"FileSystemException: FileSystemException: Exists failed, path = '/Users/niyazitoros/Applications/Visual Studio Code.app/Contents' (OS Error: Permission denied, errno = 13)"

But I don't have Visual Studio Code.app?

**Comment by putraxor** [comment]
Your flutter doctor doesn't show intellij idea , it means flutter doesn't detect your idea location

**Comment by NTMS2017** [comment]
Thanks. Overcome the issue with moving temp path from  to specific path
